# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2fb6f68f462f7cfc9fea06b1974321222bba009404e8a05757f76bedb4505b2cdf8c6bf0daf44133241a74cd58a89c641f7fcd430263303aabed8d4d90901495

test:
  secret_key_base: 8892c59574ef6ab608103268829c17a1d1e9888be470f409d8ec041b277a579a376ae7c6770f40f7c2de1dadd526cacd11d29642b9730f1f40921c93b4d2eccb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
